/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gestionproyectosacademicos.presentacion;

import java.awt.CardLayout;

/**
 *
 * @author bryan
 */
public class GUICoordinator extends javax.swing.JFrame {

    /**
     * Creates new form GUIMenu
     */
    public GUICoordinator() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpIzq = new javax.swing.JPanel();
        lblUser = new javax.swing.JLabel();
        lblCoordinator = new javax.swing.JLabel();
        sepUserCoord = new javax.swing.JSeparator();
        btnPerfil = new javax.swing.JButton();
        btnRequests = new javax.swing.JButton();
        btnMonitoring = new javax.swing.JButton();
        btnAssignment = new javax.swing.JButton();
        btnReports = new javax.swing.JButton();
        btnConnections = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        pnlDer = new javax.swing.JPanel();
        pnlPerfil = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pnlRequests = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pnlMonitoring = new javax.swing.JPanel();
        pnlAssingment = new javax.swing.JPanel();
        pnlReports = new javax.swing.JPanel();
        pnlConnections = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(960, 540));
        setSize(new java.awt.Dimension(960, 540));

        jpIzq.setBackground(new java.awt.Color(19, 45, 70));
        jpIzq.setAlignmentX(0.0F);
        jpIzq.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblUser.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblUser.setForeground(new java.awt.Color(255, 255, 255));
        lblUser.setText("Usuario");

        lblCoordinator.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCoordinator.setForeground(new java.awt.Color(255, 255, 255));
        lblCoordinator.setText("Coordinador");

        sepUserCoord.setBackground(new java.awt.Color(155, 70, 47));

        btnPerfil.setText("Perfil");
        btnPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerfilActionPerformed(evt);
            }
        });

        btnRequests.setText("Solicitudes");
        btnRequests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestsActionPerformed(evt);
            }
        });

        btnMonitoring.setText("Monitoreo");
        btnMonitoring.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMonitoringActionPerformed(evt);
            }
        });

        btnAssignment.setText("Asignación");
        btnAssignment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignmentActionPerformed(evt);
            }
        });

        btnReports.setText("Reportes");
        btnReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportsActionPerformed(evt);
            }
        });

        btnConnections.setText("Conexiones");
        btnConnections.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConnectionsActionPerformed(evt);
            }
        });

        jButton1.setText("Cerrar Sesión");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpIzqLayout = new javax.swing.GroupLayout(jpIzq);
        jpIzq.setLayout(jpIzqLayout);
        jpIzqLayout.setHorizontalGroup(
            jpIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpIzqLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpIzqLayout.createSequentialGroup()
                            .addGap(95, 95, 95)
                            .addGroup(jpIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblUser)
                                .addGroup(jpIzqLayout.createSequentialGroup()
                                    .addComponent(lblCoordinator)
                                    .addGap(14, 14, 14))))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpIzqLayout.createSequentialGroup()
                            .addGap(26, 26, 26)
                            .addComponent(jButton1))
                        .addComponent(btnReports, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jpIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sepUserCoord, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnAssignment, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                                .addComponent(btnPerfil, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnMonitoring, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRequests, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(btnConnections, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(90, 90, 90))
        );
        jpIzqLayout.setVerticalGroup(
            jpIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpIzqLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sepUserCoord, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCoordinator)
                .addGap(40, 40, 40)
                .addComponent(btnPerfil)
                .addGap(30, 30, 30)
                .addComponent(btnRequests)
                .addGap(30, 30, 30)
                .addComponent(btnMonitoring)
                .addGap(30, 30, 30)
                .addComponent(btnAssignment)
                .addGap(30, 30, 30)
                .addComponent(btnReports)
                .addGap(30, 30, 30)
                .addComponent(btnConnections)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(20, 20, 20))
        );

        getContentPane().add(jpIzq, java.awt.BorderLayout.LINE_START);

        pnlDer.setBackground(new java.awt.Color(255, 255, 255));
        pnlDer.setLayout(new java.awt.CardLayout());

        jLabel2.setText("Perfil");
        pnlPerfil.add(jLabel2);

        pnlDer.add(pnlPerfil, "card3");

        pnlRequests.setLayout(new java.awt.BorderLayout());
        pnlRequests.add(jPanel1, java.awt.BorderLayout.PAGE_END);
        pnlRequests.add(jPanel2, java.awt.BorderLayout.LINE_END);
        pnlRequests.add(jPanel3, java.awt.BorderLayout.WEST);
        pnlRequests.add(jPanel5, java.awt.BorderLayout.PAGE_START);
        pnlRequests.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        pnlRequests.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pnlDer.add(pnlRequests, "card2");
        pnlDer.add(pnlMonitoring, "card4");
        pnlDer.add(pnlAssingment, "card5");
        pnlDer.add(pnlReports, "card6");
        pnlDer.add(pnlConnections, "card7");

        getContentPane().add(pnlDer, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRequestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestsActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) pnlDer.getLayout();
        cl.show(pnlDer, "card2");
    }//GEN-LAST:event_btnRequestsActionPerformed

    private void btnPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerfilActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) pnlDer.getLayout();
        cl.show(pnlDer, "card3");
    }//GEN-LAST:event_btnPerfilActionPerformed

    private void btnMonitoringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMonitoringActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMonitoringActionPerformed

    private void btnAssignmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAssignmentActionPerformed

    private void btnReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReportsActionPerformed

    private void btnConnectionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConnectionsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConnectionsActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUICoordinator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUICoordinator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUICoordinator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUICoordinator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUICoordinator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssignment;
    private javax.swing.JButton btnConnections;
    private javax.swing.JButton btnMonitoring;
    private javax.swing.JButton btnPerfil;
    private javax.swing.JButton btnReports;
    private javax.swing.JButton btnRequests;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel jpIzq;
    private javax.swing.JLabel lblCoordinator;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPanel pnlAssingment;
    private javax.swing.JPanel pnlConnections;
    private javax.swing.JPanel pnlDer;
    private javax.swing.JPanel pnlMonitoring;
    private javax.swing.JPanel pnlPerfil;
    private javax.swing.JPanel pnlReports;
    private javax.swing.JPanel pnlRequests;
    private javax.swing.JSeparator sepUserCoord;
    // End of variables declaration//GEN-END:variables
}
