package com.mycompany.gestionproyectosacademicos.presentacion;

import com.mycompany.gestionproyectosacademicos.entities.Project;
import com.mycompany.gestionproyectosacademicos.observer.Observer;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.List;

/**
 *
 * @author Jhonatan
 */
public class GUIStudentProjectList extends javax.swing.JFrame implements Observer{

    private JTable projectTable;
    private DefaultTableModel tableModel;
    /**
     * Creates new form GUIStudentProjectList
     */
    public GUIStudentProjectList() {
        initComponents();
        initTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelDashboard = new javax.swing.JPanel();
        sepUserCoord = new javax.swing.JSeparator();
        lblUser = new javax.swing.JLabel();
        lblEstudiante = new javax.swing.JLabel();
        btnProfileStudent = new javax.swing.JButton();
        btnProjectList = new javax.swing.JButton();
        btnMyProjects = new javax.swing.JButton();
        btnCloseSessionStudent = new javax.swing.JButton();
        jPanelProjectList = new javax.swing.JPanel();
        lblTitleProjectList = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelDashboard.setBackground(new java.awt.Color(19, 45, 70));

        sepUserCoord.setBackground(new java.awt.Color(155, 70, 47));

        lblUser.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblUser.setForeground(new java.awt.Color(255, 255, 255));
        lblUser.setText("Usuario");

        lblEstudiante.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblEstudiante.setForeground(new java.awt.Color(255, 255, 255));
        lblEstudiante.setText("Estudiante");

        btnProfileStudent.setBackground(new java.awt.Color(98, 114, 129));
        btnProfileStudent.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnProfileStudent.setForeground(new java.awt.Color(255, 255, 255));
        btnProfileStudent.setLabel("Perfil");
        btnProfileStudent.setMaximumSize(new java.awt.Dimension(28, 17));
        btnProfileStudent.setMinimumSize(new java.awt.Dimension(28, 17));
        btnProfileStudent.setPreferredSize(new java.awt.Dimension(28, 17));

        btnProjectList.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnProjectList.setForeground(new java.awt.Color(19, 45, 70));
        btnProjectList.setLabel("Proyectos Disponibles");
        btnProjectList.setMaximumSize(new java.awt.Dimension(28, 17));
        btnProjectList.setMinimumSize(new java.awt.Dimension(28, 17));
        btnProjectList.setPreferredSize(new java.awt.Dimension(28, 17));

        btnMyProjects.setBackground(new java.awt.Color(98, 114, 129));
        btnMyProjects.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnMyProjects.setForeground(new java.awt.Color(255, 255, 255));
        btnMyProjects.setLabel("Mis Proyectos");
        btnMyProjects.setMaximumSize(new java.awt.Dimension(28, 17));
        btnMyProjects.setMinimumSize(new java.awt.Dimension(28, 17));
        btnMyProjects.setPreferredSize(new java.awt.Dimension(28, 17));

        btnCloseSessionStudent.setBackground(new java.awt.Color(98, 114, 129));
        btnCloseSessionStudent.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCloseSessionStudent.setForeground(new java.awt.Color(255, 255, 255));
        btnCloseSessionStudent.setLabel("Cerrar Sesíon");
        btnCloseSessionStudent.setMaximumSize(new java.awt.Dimension(75, 19));
        btnCloseSessionStudent.setMinimumSize(new java.awt.Dimension(75, 19));
        btnCloseSessionStudent.setPreferredSize(new java.awt.Dimension(75, 19));
        btnCloseSessionStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseSessionStudentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDashboardLayout = new javax.swing.GroupLayout(jPanelDashboard);
        jPanelDashboard.setLayout(jPanelDashboardLayout);
        jPanelDashboardLayout.setHorizontalGroup(
            jPanelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDashboardLayout.createSequentialGroup()
                        .addComponent(btnProfileStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanelDashboardLayout.createSequentialGroup()
                        .addComponent(btnProjectList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanelDashboardLayout.createSequentialGroup()
                        .addComponent(btnMyProjects, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(jPanelDashboardLayout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(lblEstudiante)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanelDashboardLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(jPanelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sepUserCoord, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUser)
                    .addComponent(btnCloseSessionStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        jPanelDashboardLayout.setVerticalGroup(
            jPanelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDashboardLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sepUserCoord, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEstudiante)
                .addGap(56, 56, 56)
                .addComponent(btnProfileStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnProjectList, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnMyProjects, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(btnCloseSessionStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        lblTitleProjectList.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblTitleProjectList.setForeground(new java.awt.Color(19, 45, 70));
        lblTitleProjectList.setText("Proyectos Disponibles");

        javax.swing.GroupLayout jPanelProjectListLayout = new javax.swing.GroupLayout(jPanelProjectList);
        jPanelProjectList.setLayout(jPanelProjectListLayout);
        jPanelProjectListLayout.setHorizontalGroup(
            jPanelProjectListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProjectListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitleProjectList)
                .addContainerGap(370, Short.MAX_VALUE))
        );
        jPanelProjectListLayout.setVerticalGroup(
            jPanelProjectListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProjectListLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTitleProjectList)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelProjectList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelProjectList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initTable() {
        tableModel = new DefaultTableModel(new Object[]{"ID", "Nombre", "Descripción", "Estado"}, 0);
        projectTable = new JTable();
        jPanelProjectList.add(new JScrollPane(projectTable));
    }
    
    private void btnCloseSessionStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseSessionStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCloseSessionStudentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIStudentProjectList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIStudentProjectList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIStudentProjectList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIStudentProjectList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIStudentProjectList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCloseSessionStudent;
    private javax.swing.JButton btnMyProjects;
    private javax.swing.JButton btnProfileStudent;
    private javax.swing.JButton btnProjectList;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelDashboard;
    private javax.swing.JPanel jPanelProjectList;
    private javax.swing.JLabel lblEstudiante;
    private javax.swing.JLabel lblTitleProjectList;
    private javax.swing.JLabel lblUser;
    private javax.swing.JSeparator sepUserCoord;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Project project) {
        tableModel.addRow(new Object[]{
            project.getId(),
            project.getName(),
            project.getDescription(),
            project.getState()
        });
    }
}
